import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Header, Loading, Providers } from '@/shared/components';
import { Suspense } from 'react';

const geistSans = localFont({
  src: './fonts/Campusotl.woff',
  variable: '--font-geist-sans',
  weight: '400',
});
const geistMono = localFont({
  src: './fonts/Karla.woff',
  variable: '--font-geist-mono',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'SWAPI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
        <main className="min-h-screen background max-w-[1440px]">
          <Providers>
            <Header />
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </Providers>
        </main>
      </body>
    </html>
  );
}
